//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoReservation.Dal
{
    using System;
    
    public enum AutoKlasse : int
    {
        LuxusklasseAuto = 0,
        MittelklasseAuto = 1,
        StandardAuto = 2
    }
}
